# Generated by Django 3.2.11 on 2022-02-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduce', models.FileField(upload_to='introduce/')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
