# Generated by Django 3.2.11 on 2022-02-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFile',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
